# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Generate Version Info
        run: |
          echo "VITE_DEPLOY_TIME=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> .env
          echo "VITE_COMMIT_HASH=$(git rev-parse HEAD)" >> .env
          echo "VITE_LAST_COMMIT_DATE=$(git log -1 --pretty=format:%ci)" >> .env
          echo "VITE_COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)" >> .env
          echo "VITE_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)" >> .env
          echo "VITE_COMMIT_AUTHOR=$(git log -1 --pretty=format:%an)" >> .env
          echo "VITE_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> .env
          echo "VITE_TOTAL_COMMITS=$(git rev-list --count HEAD)" >> .env

      - name: NPM CI
        run: npm ci
      - name: Build
        run: npm run build
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4