export enum EValidationMessage {
  IS_NOT_EMPTY = 'validation.IS_NOT_EMPTY',
  MIN = 'validation.MIN',
  IS_NUMBER = 'validation.IS_NUMBER',
  TICKET_ID_MUST_BE_UUID = 'validation.TICKET_ID_MUST_BE_UUID',
  IS_IN_STATUS = 'validation.IS_IN_STATUS',
  IS_DATE_STRING = 'validation.IS_DATE_STRING',
  IS_INT = 'validation.IS_INT',
  IS_ARRAY = 'validation.IS_ARRAY',
  IS_IN_SORT = 'validation.IS_IN_SORT',
  IS_BOOLEAN = 'validation.IS_BOOLEAN',
  IS_UUID = 'validation.IS_UUID',
  IS_FILES = 'validation.IS_FILES',
  HAS_MIME_TYPE = 'validation.HAS_MIME_TYPE',
  IS_EMAIL = 'validation.IS_EMAIL',
  PASSWORD_DO_NOT_MATCH = 'validation.PASSWORD_DO_NOT_MATCH',
}
