services:
  offline-first-pock-backend:
    container_name: Offline-first-pock-Backend
    restart: always
    build: .
    ports: 
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock