services:
  offlineFirstPock-backend:
    container_name: OfflineFirstPock-Backend
    restart: always
    build: .
    ports: 
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock